apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewpage
  labels:
    app: viewpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viewpage
  template:
    metadata:
      labels:
        app: viewpage
    spec:
      containers:
        - name: viewpage
          image: 247785678011.dkr.ecr.us-east-2.amazonaws.com/viewpage:1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/roomviews'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/roomviews'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5